version: "3.8"

services:
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Host:Container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
